### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by NightMachinery** [candh/glyrics#1]
```
glyrics sway                                                                 ✔  10527  20:15:07
◞ Searching for tracks...undefined:1
<html><head><meta http-equiv="Content-Type" content="text/html; charset=windows-1256"><title>RC1-5(1)</title></head><body><iframe src="http://10.10.34.35:80" style="width: 100%; height: 100%" scrolling="no" marginwidth="0" marginheight="0" frameborder="0" vspace="0" hspace="0"></iframe></body></html>
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request.request [as _callback] (/usr/local/lib/node_modules/glyrics/genius.js:48:27)
    at Request.self.callback (/usr/local/lib/node_modules/glyrics/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/glyrics/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/glyrics/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1085:12)
```

**Comment by candh** [comment]
@NightMachinary i can't reproduce this... it works fine.. for me.
I have pushed a small update tho, unrelated to this bug (or at least i think). However, you should update and see if you can reproduce the bug. 

Thanks for opening an issue!

**Comment by candh** [comment]
Looking closely at the output however, seems like you're not getting the correct response when hitting the api... Seems like a problem with _your_ network or stuff..
